(function () {
  "use strict";

  /* ─── PART I: MULTIPLE CHOICE (10 items) ─────────────────────────── */
  const MC_QUESTIONS = [
    {
      n: 1,
      q: "What does the term 'Digital' refer to in electronics?",
      opts: [
        "The use of light in computing",
        "The measurement of electrical current",
        "The way computers perform operations by counting digits",
        "The process of converting sound to text",
      ],
    },
    {
      n: 2,
      q: "Which of the following is an example of an analog signal?",
      opts: ["Binary Signal", "Octal Signal", "Hexadecimal Signal", "Temperature"],
    },
    {
      n: 3,
      q: "What type of signal has only a finite number of distinct values?",
      opts: ["Analog Signal", "Digital Signal", "Continuous Signal", "Natural Signal"],
    },
    {
      n: 4,
      q: "Which device converts analog signals into digital signals?",
      opts: ["Transducer", "Amplifier", "Filter", "A to D Converter"],
    },
    {
      n: 5,
      q: "Which of the following is an example of a digital system?",
      opts: ["Amplifier", "Motor speed controller", "Microprocessor", "Television receiver"],
    },
    {
      n: 6,
      q: "Which of the following is a disadvantage of analog systems?",
      opts: ["More accuracy", "Possible storage of information", "More noise effect", "More versatility"],
    },
    {
      n: 7,
      q: "What circuit element stores a single bit of data (0 or 1)?",
      opts: ["Counter", "Register", "Microprocessor", "Flip-flop"],
    },
    {
      n: 8,
      q: "Which of the following correctly describes an analog signal graph?",
      opts: [
        "Sharp rectangular blocks jumping between 0 and 1",
        "A smooth and continuous curve changing over time",
        "A flat horizontal line with no change",
        "A series of discrete steps",
      ],
    },
    {
      n: 9,
      q: "Which of the following is an advantage of digital systems?",
      opts: ["More noise effect", "More distortion", "Less accuracy", "Possible storage of information"],
    },
    {
      n: 10,
      q: "Which statement best compares analog and digital signals?",
      opts: [
        "Analog signals have finite values; digital signals have infinite values",
        "Digital signals are continuous; analog signals are discrete",
        "Analog signals have infinite values; digital signals have finite values",
        "Both signals are generated by A to D converters",
      ],
    },
  ];

  const MC_ANSWERS = ["C", "D", "B", "D", "C", "C", "D", "B", "D", "C"];

  /* ─── PART II: IDENTIFICATION (5 items) ──────────────────────────── */
  const ID_QUESTIONS = [
    "I am a physical quantity that carries information and is a function of one or more independent variables. What am I?",
    "I am a digital circuit element that temporarily stores binary data in a computer. What am I?",
    "I am the device that converts physical quantities into analog signals. What am I?",
    "I am a type of digital signal that uses base-16 values ranging from 0–9 and A–F. What am I?",
    "I am the main processing unit of a digital computer that handles instructions. What am I?",
  ];

  const ID_KEYS = [
    ["signal"],
    ["register", "registers"],
    ["transducer"],
    ["hexadecimal signal", "hexadecimal"],
    ["microprocessor"],
  ];

  const ID_OFFICIAL = [
    "Signal",
    "Register",
    "Transducer",
    "Hexadecimal Signal",
    "Microprocessor",
  ];

  /* ─── PART III: ENUMERATION (5 items) ────────────────────────────── */
  const ENUM_STEMS = [
    "Enumerate the 2 types of signals discussed in the lesson.",
    "Enumerate 4 examples of analog signals.",
    "Enumerate the 4 examples of digital systems.",
    "Enumerate the 3 types of digital signals.",
    "Enumerate 3 disadvantages of analog systems.",
  ];

  const ENUM_OFFICIAL = [
    "Analog Signal; Digital Signal",
    "Any 4 of: Temperature, Pressure, Distance, Sound, Voltage, Current, Power",
    "Registers; Flip-flop; Counters; Microprocessors",
    "Binary Signal; Octal Signal; Hexadecimal Signal",
    "Any 3 of: Less accuracy, Less versatility, More noise effect, More distortion, More effect of weather",
  ];

  const ENUM_KEY_DETAIL = [
    {
      title: "1. Two types of signals",
      lines: ["Analog Signal", "Digital Signal"],
    },
    {
      title: "2. Four examples of analog signals (any 4 of 7)",
      lines: ["Temperature", "Pressure", "Distance", "Sound", "Voltage", "Current", "Power"],
    },
    {
      title: "3. Four examples of digital systems",
      lines: ["Registers", "Flip-flop", "Counters", "Microprocessors"],
    },
    {
      title: "4. Three types of digital signals",
      lines: ["Binary Signal", "Octal Signal", "Hexadecimal Signal"],
    },
    {
      title: "5. Three disadvantages of analog systems (any 3 of 5)",
      lines: [
        "Less accuracy",
        "Less versatility",
        "More noise effect",
        "More distortion",
        "More effect of weather",
      ],
    },
  ];

  /* ─── GRADING HELPERS ────────────────────────────────────────────── */
  const LETTERS = ["A", "B", "C", "D"];

  function normalize(s) {
    return String(s || "")
      .toLowerCase()
      .replace(/['']/g, "'")
      .replace(/\//g, " ")
      .replace(/-/g, " ")
      .replace(/[()[\]]/g, "")
      .replace(/\s+/g, " ")
      .replace(/[.,;:]/g, "")
      .trim();
  }

  function idMatches(input, acceptedList) {
    const n = normalize(input);
    if (!n) return false;
    return acceptedList.some(function (acc) {
      const a = normalize(acc);
      if (n === a) return true;
      if (a.length >= 4 && (n.includes(a) || a.includes(n))) return true;
      return false;
    });
  }

  function parseEnumLines(raw) {
    return String(raw || "")
      .split(/\r?\n/)
      .map(function (line) {
        return normalize(line.replace(/^\s*\d+[\.\)]\s*/, "").replace(/^[-*•]\s*/, ""));
      })
      .filter(Boolean);
  }

  function enumTokenMatch(userLineNorm, phrase) {
    const p = normalize(phrase);
    if (!p || !userLineNorm) return false;
    if (userLineNorm === p) return true;
    if (p.length >= 4 && userLineNorm.includes(p)) return true;
    return false;
  }

  function enumLineMatchNorm(userLineNorm, keyAlts) {
    if (!userLineNorm) return false;
    return keyAlts.some(function (key) {
      return enumTokenMatch(userLineNorm, key);
    });
  }

  function enumSetCorrect(userLines, keysPerLine) {
    if (userLines.length < keysPerLine.length) return false;
    const used = {};
    for (let e = 0; e < keysPerLine.length; e++) {
      let found = false;
      for (let u = 0; u < userLines.length; u++) {
        if (used[u]) continue;
        if (enumLineMatchNorm(userLines[u], keysPerLine[e])) {
          used[u] = true;
          found = true;
          break;
        }
      }
      if (!found) return false;
    }
    return true;
  }

  // For "any N of M" sets — needs at least N matches from a larger pool
  function enumAnyNofM(userLines, needed, pool) {
    let matched = 0;
    const used = {};
    for (let p = 0; p < pool.length; p++) {
      for (let u = 0; u < userLines.length; u++) {
        if (used[u]) continue;
        if (enumTokenMatch(userLines[u], pool[p])) {
          used[u] = true;
          matched++;
          break;
        }
      }
    }
    return matched >= needed;
  }

  function enumItemCorrect(idx, raw) {
    const userLines = parseEnumLines(raw);
    if (userLines.length === 0) return false;
    switch (idx) {
      case 0: // 2 types of signals
        return enumSetCorrect(userLines, [
          ["analog signal", "analog"],
          ["digital signal", "digital"],
        ]);
      case 1: // any 4 of 7 analog signal examples
        return (
          userLines.length >= 4 &&
          enumAnyNofM(userLines, 4, [
            "temperature",
            "pressure",
            "distance",
            "sound",
            "voltage",
            "current",
            "power",
          ])
        );
      case 2: // 4 digital systems
        return enumSetCorrect(userLines, [
          ["register", "registers"],
          ["flip flop", "flipflop", "flip-flop"],
          ["counter", "counters"],
          ["microprocessor", "microprocessors"],
        ]);
      case 3: // 3 types of digital signals
        return enumSetCorrect(userLines, [
          ["binary signal", "binary"],
          ["octal signal", "octal"],
          ["hexadecimal signal", "hexadecimal"],
        ]);
      case 4: // any 3 of 5 disadvantages
        return (
          userLines.length >= 3 &&
          enumAnyNofM(userLines, 3, [
            "less accuracy",
            "accuracy",
            "less versatility",
            "versatility",
            "noise",
            "distortion",
            "weather",
          ])
        );
      default:
        return false;
    }
  }

  /* ─── GLOW HELPERS ───────────────────────────────────────────────── */
  function applyMcItemGlow(qnum) {
    const idx = MC_QUESTIONS.findIndex(function (q) { return q.n === qnum; });
    if (idx < 0) return;
    const block = document.querySelector('.mc-item[data-q="' + qnum + '"]');
    if (!block) return;
    block.classList.remove("answer-correct", "answer-incorrect");
    const selected = document.querySelector('input[name="mc_' + qnum + '"]:checked');
    if (!selected) return;
    block.classList.add(selected.value === MC_ANSWERS[idx] ? "answer-correct" : "answer-incorrect");
  }

  function applyIdItemGlow(idNum) {
    const idx = idNum - 1;
    if (idx < 0 || idx >= ID_KEYS.length) return;
    const block = document.querySelector('.id-item[data-id="' + idNum + '"]');
    const input = document.getElementById("id_" + idNum);
    if (!block || !input) return;
    block.classList.remove("answer-correct", "answer-incorrect");
    if (!String(input.value).trim()) return;
    block.classList.add(idMatches(input.value, ID_KEYS[idx]) ? "answer-correct" : "answer-incorrect");
  }

  function applyEnumGlow(num) {
    const idx = num - 1;
    if (idx < 0 || idx >= ENUM_STEMS.length) return;
    const block = document.querySelector('.enum-item[data-enum="' + num + '"]');
    const ta = document.getElementById("enum_" + num);
    if (!block || !ta) return;
    block.classList.remove("answer-correct", "answer-incorrect");
    if (!String(ta.value).trim()) return;
    block.classList.add(enumItemCorrect(idx, ta.value) ? "answer-correct" : "answer-incorrect");
  }

  /* ─── RENDER FUNCTIONS ───────────────────────────────────────────── */
  function renderMC() {
    const container = document.getElementById("mc-container");
    const frag = document.createDocumentFragment();
    MC_QUESTIONS.forEach(function (item) {
      const wrap = document.createElement("div");
      wrap.className = "mc-item";
      wrap.setAttribute("data-q", String(item.n));
      const stem = document.createElement("p");
      stem.className = "mc-stem";
      stem.textContent = item.n + ". " + item.q;
      const opts = document.createElement("div");
      opts.className = "mc-options";
      item.opts.forEach(function (text, oi) {
        const lab = document.createElement("label");
        const radio = document.createElement("input");
        radio.type = "radio";
        radio.name = "mc_" + item.n;
        radio.value = LETTERS[oi];
        const span = document.createElement("span");
        span.textContent = LETTERS[oi] + ") " + text;
        radio.addEventListener("change", function () { applyMcItemGlow(item.n); });
        lab.appendChild(radio);
        lab.appendChild(span);
        opts.appendChild(lab);
      });
      wrap.appendChild(stem);
      wrap.appendChild(opts);
      frag.appendChild(wrap);
    });
    container.appendChild(frag);
  }

  function renderID() {
    const container = document.getElementById("id-container");
    const frag = document.createDocumentFragment();
    ID_QUESTIONS.forEach(function (text, i) {
      const num = i + 1;
      const wrap = document.createElement("div");
      wrap.className = "id-item";
      wrap.setAttribute("data-id", String(num));
      const lab = document.createElement("label");
      lab.setAttribute("for", "id_" + num);
      lab.textContent = num + ". " + text;
      const input = document.createElement("input");
      input.type = "text";
      input.name = "id_" + num;
      input.id = "id_" + num;
      input.setAttribute("autocomplete", "off");
      input.addEventListener("input", function () { applyIdItemGlow(num); });
      wrap.appendChild(lab);
      wrap.appendChild(input);
      frag.appendChild(wrap);
    });
    container.appendChild(frag);
  }

  function renderEnum() {
    const container = document.getElementById("enum-container");
    if (!container) return;
    const frag = document.createDocumentFragment();
    ENUM_STEMS.forEach(function (stem, i) {
      const num = i + 1;
      const wrap = document.createElement("div");
      wrap.className = "enum-item";
      wrap.setAttribute("data-enum", String(num));
      const lab = document.createElement("label");
      lab.setAttribute("for", "enum_" + num);
      lab.textContent = num + ". " + stem;
      const ta = document.createElement("textarea");
      ta.id = "enum_" + num;
      ta.name = "enum_" + num;
      ta.setAttribute("rows", "5");
      ta.setAttribute("autocomplete", "off");
      ta.addEventListener("input", function () { applyEnumGlow(num); });
      wrap.appendChild(lab);
      wrap.appendChild(ta);
      frag.appendChild(wrap);
    });
    container.appendChild(frag);
  }

  function renderAnswerKey() {
    const el = document.getElementById("answer-key-content");

    // MC key
    const mcTitle = document.createElement("p");
    mcTitle.innerHTML = "<strong>Part I — Multiple Choice</strong>";
    const mcGrid = document.createElement("div");
    mcGrid.className = "key-grid";
    MC_ANSWERS.forEach(function (ans, i) {
      const d = document.createElement("div");
      d.textContent = (i + 1) + ". " + ans;
      mcGrid.appendChild(d);
    });

    // ID key
    const idTitle = document.createElement("p");
    idTitle.innerHTML = "<strong>Part II — Identification</strong>";
    idTitle.style.marginTop = "1rem";
    const idGrid = document.createElement("div");
    idGrid.className = "key-grid";
    ID_OFFICIAL.forEach(function (ans, i) {
      const d = document.createElement("div");
      d.textContent = (i + 1) + ". " + ans;
      idGrid.appendChild(d);
    });

    el.innerHTML = "";
    el.appendChild(mcTitle);
    el.appendChild(mcGrid);
    el.appendChild(idTitle);
    el.appendChild(idGrid);

    // Enum key
    const enTitle = document.createElement("p");
    enTitle.innerHTML = "<strong>Part III — Enumeration</strong>";
    enTitle.style.marginTop = "1rem";
    const enWrap = document.createElement("div");
    ENUM_KEY_DETAIL.forEach(function (block) {
      const sec = document.createElement("div");
      sec.style.marginTop = "0.85rem";
      const ht = document.createElement("p");
      ht.style.margin = "0 0 0.35rem";
      ht.style.fontWeight = "600";
      ht.textContent = block.title;
      sec.appendChild(ht);
      const ul = document.createElement("ul");
      ul.style.margin = "0";
      ul.style.paddingLeft = "1.25rem";
      block.lines.forEach(function (ln) {
        const li = document.createElement("li");
        li.textContent = ln;
        ul.appendChild(li);
      });
      sec.appendChild(ul);
      enWrap.appendChild(sec);
    });
    el.appendChild(enTitle);
    el.appendChild(enWrap);
  }

  /* ─── GRADING ────────────────────────────────────────────────────── */
  function clearAnswerGlows() {
    document.querySelectorAll(".mc-item, .id-item, .enum-item").forEach(function (el) {
      el.classList.remove("answer-correct", "answer-incorrect");
    });
  }

  function escapeHtml(t) {
    const div = document.createElement("div");
    div.textContent = t;
    return div.innerHTML;
  }

  function grade() {
    clearAnswerGlows();

    let mcCorrect = 0;
    const mcRows = [];
    MC_QUESTIONS.forEach(function (item, i) {
      const selected = document.querySelector('input[name="mc_' + item.n + '"]:checked');
      const user = selected ? selected.value : "—";
      const correct = MC_ANSWERS[i];
      const ok = user === correct;
      if (ok) mcCorrect++;
      mcRows.push({ num: item.n, user: user, correct: correct, ok: ok });
    });

    let idCorrect = 0;
    const idRows = [];
    for (let i = 0; i < ID_QUESTIONS.length; i++) {
      const input = document.getElementById("id_" + (i + 1));
      const raw = input ? input.value : "";
      const ok = idMatches(raw, ID_KEYS[i]);
      if (ok) idCorrect++;
      idRows.push({ num: i + 1, user: raw.trim() || "—", ok: ok, official: ID_OFFICIAL[i] });
    }

    let enumCorrect = 0;
    const enumRows = [];
    for (let i = 0; i < ENUM_STEMS.length; i++) {
      const ta = document.getElementById("enum_" + (i + 1));
      const raw = ta ? ta.value : "";
      const ok = enumItemCorrect(i, raw);
      if (ok) enumCorrect++;
      enumRows.push({ num: i + 1, user: raw.trim() || "—", ok: ok, official: ENUM_OFFICIAL[i] });
    }

    const totalMC = MC_QUESTIONS.length;
    const totalID = ID_QUESTIONS.length;
    const totalEnum = ENUM_STEMS.length;
    const total = totalMC + totalID + totalEnum;
    const score = mcCorrect + idCorrect + enumCorrect;

    document.getElementById("results-summary").textContent =
      "Score: " + score + " / " + total +
      " (Part I: " + mcCorrect + "/" + totalMC +
      "; Part II: " + idCorrect + "/" + totalID +
      "; Part III: " + enumCorrect + "/" + totalEnum + ").";

    let html = "<h3>Part I detail</h3><table><thead><tr><th>#</th><th>Your answer</th><th>Key</th></tr></thead><tbody>";
    mcRows.forEach(function (r) {
      html += "<tr class='" + (r.ok ? "correct" : "incorrect") + "'><td>" + r.num + "</td><td>" + r.user + "</td><td>" + r.correct + "</td></tr>";
    });
    html += "</tbody></table>";

    html += "<h3>Part II detail</h3><table><thead><tr><th>#</th><th>Your answer</th><th>Status</th></tr></thead><tbody>";
    idRows.forEach(function (r) {
      html += "<tr class='" + (r.ok ? "correct" : "incorrect") + "'><td>" + r.num + "</td><td>" + escapeHtml(r.user) + "</td><td>" + (r.ok ? "Correct" : "Incorrect — key: " + escapeHtml(r.official)) + "</td></tr>";
    });
    html += "</tbody></table>";

    html += "<h3>Part III detail</h3><table><thead><tr><th>#</th><th>Your answer</th><th>Key (summary)</th></tr></thead><tbody>";
    enumRows.forEach(function (r) {
      const u = r.user.length > 200 ? r.user.slice(0, 200) + "…" : r.user;
      html += "<tr class='" + (r.ok ? "correct" : "incorrect") + "'><td>" + r.num + "</td><td>" + escapeHtml(u) + "</td><td>" + escapeHtml(r.official) + "</td></tr>";
    });
    html += "</tbody></table>";
    document.getElementById("results-detail").innerHTML = html;

    mcRows.forEach(function (r) {
      const block = document.querySelector('.mc-item[data-q="' + r.num + '"]');
      if (block) block.classList.add(r.ok ? "answer-correct" : "answer-incorrect");
    });
    idRows.forEach(function (r) {
      const block = document.querySelector('.id-item[data-id="' + r.num + '"]');
      if (block) block.classList.add(r.ok ? "answer-correct" : "answer-incorrect");
    });
    enumRows.forEach(function (r) {
      const block = document.querySelector('.enum-item[data-enum="' + r.num + '"]');
      if (block) block.classList.add(r.ok ? "answer-correct" : "answer-incorrect");
    });

    document.getElementById("results-panel").classList.remove("hidden");
    document.getElementById("results-panel").scrollIntoView({ behavior: "smooth", block: "start" });
  }

  /* ─── INIT ───────────────────────────────────────────────────────── */
  function init() {
    renderMC();
    renderID();
    renderEnum();
    renderAnswerKey();

    const today = new Date().toISOString().slice(0, 10);
    const dateInput = document.getElementById("exam_date");
    if (dateInput) dateInput.value = today;

    document.getElementById("exam-form").addEventListener("submit", function (e) {
      e.preventDefault();
      grade();
    });

    document.getElementById("btn-reset").addEventListener("click", function () {
      if (!confirm("Clear all answers? This cannot be undone.")) return;
      clearAnswerGlows();
      document.getElementById("exam-form").reset();
      document.getElementById("results-panel").classList.add("hidden");
      if (dateInput) dateInput.value = today;
    });

    document.getElementById("btn-print").addEventListener("click", function () {
      window.print();
    });

    document.getElementById("btn-toggle-key").addEventListener("click", function () {
      const key = document.getElementById("answer-key-content");
      const hidden = key.classList.toggle("hidden");
      this.textContent = hidden ? "Show Answer Key" : "Hide Answer Key";
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
